FROM node:18-alpine
WORKDIR /app
# Copie d'abord seulement les fichiers de dépendances
COPY package.json package-lock.json ./
RUN npm install
# Puis copie le reste du code
COPY . .
CMD ["npm", "run", "dev"]
