FROM node:18-alpine

RUN apk add --no-cache bash git

WORKDIR /app

RUN corepack enable && corepack prepare yarn@stable --activate

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn .yarn

RUN yarn install

COPY . .

EXPOSE 5173

CMD ["yarn", "dev", "--host"]
