version: '3.8'

services:
  # --- Client Service ---
  client:
    build:
      context: ./Client
      dockerfile: dockerfile.client
    ports:
      - "5173:5173"  # Port typique pour Vite/React
      - "4173:4173"  # Port de prévisualisation
    restart: unless-stopped
    networks:
      - f_brain_network

  # --- Server Service ---
  server:
    build:
      context: ./server
      dockerfile: dockerfile.server
    ports:
      - "8000:8000"  # Backend API
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret  
      - POSTGRES_DB=mydb
    depends_on:
      - client
      - db
    networks:
      - f_brain_network

  # --- PostgreSQL Service ---
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: secret 
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"  # Port PostgreSQL
    networks:
      - f_brain_networki

  # --- Monitoring Service ---
  monitoring:
    build:
      context: ./Monitoring
      dockerfile: dockerfile.moni
    ports:
      - "9090:9090"  # Prometheus (exemple)
      - "3000:3000"  # Grafana (exemple)
    networks:
      - f_brain_network

  # --- Proxy (NGINX) ---
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf  
    depends_on:
      - client
      - server
      - monitoring 
    networks:
      - f_brain_network

# --- Réseau Docker ---
networks:
  f_brain_network:
    driver: bridge
