FROM python:3.13-slim

WORKDIR /app

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    build-essential gcc libpq-dev curl \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN pip install poetry==2.1.2

ENV POETRY_VIRTUALENVS_CREATE=false

COPY pyproject.toml poetry.lock ./

RUN poetry install --no-interaction --no-ansi --no-root

COPY . .

EXPOSE 8000

CMD ["gunicorn", "server_config.wsgi:application", "--bind", "0.0.0.0:8000"]
